import { test, expect } from '@playwright/test';

test('opens the public landing page and sends the button directly to WhatsApp with Hi', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText("Turn client testimonials into new enquiries.");
  const link = page.getByRole('link', { name: 'Paste one review.' });
  await expect(link).toHaveAttribute('href', /^https:\/\/wa\.me\/[1-9]\d{7,14}\?text=Hi$/);
  await expect(link).not.toHaveAttribute('aria-disabled');
  const target = await link.getAttribute('href');
  let clickedTarget: string | undefined;
  await page.route('https://wa.me/**', async route => {
    clickedTarget = route.request().url();
    await route.abort(); // Prove the outgoing link; real phone handoff and sending remain owner checks.
  });
  await link.click();
  await expect.poll(() => clickedTarget).toBe(target);
  expect(errors).toEqual([]);
  console.log('PASS: live 390px page; button navigates directly to wa.me with text=Hi; no JavaScript errors. Actual phone handoff/reply requires an owner phone check.');
});

test('shows a moving phone arch with tap expansion and the same compact group scene', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce', baseURL: process.env.LANDING_TEST_URL ?? 'https://giant-platypus-592.convex.site' });
  const page = await context.newPage();
  await page.goto('/');
  await page.evaluate(() => document.fonts.ready);
  await expect(page.getByRole('link', { name: 'Paste one review.' })).toHaveAttribute('href', /^https:\/\/wa\.me\/[1-9]\d{7,14}\?text=Hi$/);
  await expect(page.getByRole('link', { name: 'Paste one review.' })).not.toHaveAttribute('aria-disabled');
  await expect(page.getByRole('heading', { name: 'How it works' })).toBeVisible();
  await expect(page.locator('img.lifestyle')).toBeVisible();
  await expect(page.getByText('Engrace 2 Owners')).toBeVisible();
  await expect(page.locator('.group-header')).not.toContainText('Example previews');
  await expect(page.locator('.photo-panel .annotation')).toHaveCount(0);
  await expect(page.locator('.group-reply')).toContainText('@Mayuri, what are your batch timings?');
  await expect(page.locator('.group-reply .mention')).toBeVisible();
  expect(await page.locator('.group-reply').evaluate(e => { const chat = e.closest('.photo-panel')!.getBoundingClientRect(); return e.getBoundingClientRect().bottom <= chat.bottom; })).toBe(true);
  await expect(page.locator('.group-reply blockquote')).toContainText('Priya');
  expect(await page.locator('img.lifestyle').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(await page.locator('.photo-panel').evaluate(e => e.getBoundingClientRect().height)).toBeLessThanOrEqual(540);
  await expect(page.getByRole('button', { name: 'text message', exact: true })).toHaveAttribute('aria-current', 'true');
  expect(await page.locator('.text-card').evaluate(e => e.getBoundingClientRect().width)).toBeLessThanOrEqual(241);
  const phoneGaps = await page.locator('.text-card, .voice-card, .video-card').evaluateAll(es => {
    const rs = es.map(e => e.getBoundingClientRect()).sort((a,b) => a.left-b.left);
    return rs.slice(1).map((r,i) => r.left-rs[i].right);
  });
  expect(Math.min(...phoneGaps)).toBeGreaterThan(15);
  await page.screenshot({ path: 'M6_LANDING_390.png', fullPage: true });
  const carousel = page.locator('.coverflow');
  await carousel.scrollIntoViewIfNeeded();
  const box = await page.locator('.text-card').boundingBox();
  const touch = await context.newCDPSession(page);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: box!.x + 190, y: box!.y + 110 }] });
  for (let i = 1; i <= 10; i++) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: box!.x + 190 - i * 16, y: box!.y + 110 }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.getByRole('button', { name: 'voice note', exact: true })).toHaveAttribute('aria-current', 'true');
  const voice = page.locator('.voice-card');
  const voiceBox = await voice.boundingBox();
  await page.touchscreen.tap(voiceBox!.x + voiceBox!.width / 2, voiceBox!.y + voiceBox!.height / 2);
  await expect(voice).toHaveClass(/is-selected/);
  await expect.poll(() => voice.evaluate(e => e.style.transform)).toContain('scale(1.04)');
  await expect(carousel).toHaveAttribute('data-paused', 'true');
  const expandedBox = await voice.boundingBox();
  await page.touchscreen.tap(expandedBox!.x + expandedBox!.width / 2, expandedBox!.y + expandedBox!.height / 2);
  await expect(voice).not.toHaveClass(/is-selected/);
  await page.getByRole('button', { name: 'before/after photo', exact: true }).click();
  await expect(page.getByRole('button', { name: 'before/after photo', exact: true })).toHaveAttribute('aria-current', 'true');
  await page.locator('.before-after-preview img').evaluate((img: HTMLImageElement) => img.decode());
  await expect(page.locator('.before-card')).toBeVisible();
  expect(await page.locator('.before-card').evaluate(e => e.getBoundingClientRect().bottom < document.querySelector('.example-label')!.getBoundingClientRect().top)).toBe(true);
  await page.screenshot({ path: 'M6_BEFORE_AFTER_390.png', fullPage: true });
  const phoneScene = await page.locator('.group-thread').evaluate(e => ({ display: getComputedStyle(e).display, direction: getComputedStyle(e).flexDirection, quoteHidden: getComputedStyle(e.querySelector('blockquote p')!).display, replyOrder: getComputedStyle(e.querySelector('.group-reply')!).order, trailingHeight: e.querySelector('.group-trailing')!.getBoundingClientRect().height }));
  await page.setViewportSize({ width: 1440, height: 1000 });
  expect(await page.locator('.group-thread').evaluate(e => ({ display: getComputedStyle(e).display, direction: getComputedStyle(e).flexDirection, quoteHidden: getComputedStyle(e.querySelector('blockquote p')!).display, replyOrder: getComputedStyle(e.querySelector('.group-reply')!).order, trailingHeight: e.querySelector('.group-trailing')!.getBoundingClientRect().height }))).toEqual(phoneScene);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Privacy policy' }).click();
  await expect(page.getByRole('heading', { name: 'Privacy policy' })).toBeVisible();
  await expect(page.locator('body')).toContainText('Voice notes are deleted once transcribed.');
  // The phone layout must still show a card if JavaScript does not load.
  const fallback = await browser.newContext({ viewport: { width: 390, height: 844 }, javaScriptEnabled: false, baseURL: process.env.LANDING_TEST_URL ?? 'https://giant-platypus-592.convex.site' });
  const fallbackPage = await fallback.newPage(); await fallbackPage.goto('/');
  await expect(fallbackPage.locator('.text-card')).toBeVisible();
  expect(await fallbackPage.locator('.text-card').evaluate(e => { const r = e.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && getComputedStyle(e).opacity === '1'; })).toBe(true);
  await fallback.close();
  const auto = await context.newPage(); await auto.emulateMedia({ reducedMotion: 'no-preference' }); await auto.goto('/');
  const autoFirstX = await auto.locator('.text-card').evaluate(e => e.getBoundingClientRect().left);
  await expect.poll(() => auto.locator('.text-card').evaluate(e => e.getBoundingClientRect().left)).toBeLessThan(autoFirstX - 4);
  expect(await auto.locator('.text-card').evaluate(e => e.style.transform)).not.toContain('rotateY');
  await expect(auto.getByRole('button', { name: 'voice note', exact: true })).toHaveAttribute('aria-current', 'true', { timeout: 9000 });
  await expect.poll(() => auto.locator('.voice-card').evaluate(e => e.getBoundingClientRect().left), { timeout: 3000 }).toBeGreaterThan(20);
  await expect.poll(() => auto.locator('.voice-card').evaluate(e => e.getBoundingClientRect().right), { timeout: 3000 }).toBeLessThan(390);
  await auto.emulateMedia({ reducedMotion: 'reduce' });
  const toggle = auto.locator('#carousel-toggle');
  await expect(toggle).toHaveText('▷');
  await expect(auto.locator('.coverflow')).toHaveAttribute('data-paused', 'true');
  // iPhone's Reduce Motion must not make the existing Play control ineffective.
  await toggle.click();
  await expect(auto.locator('.coverflow')).toHaveAttribute('data-paused', 'false');
  const afterPlayX = await auto.locator('.text-card').evaluate(e => e.getBoundingClientRect().left);
  await expect.poll(() => auto.locator('.text-card').evaluate(e => e.getBoundingClientRect().left)).toBeLessThan(afterPlayX - 4);
  await auto.close(); await context.close();
  console.log('PASS: 390px touch browser: visible cards even without JavaScript, touch swipe, tap pause/expansion, dot navigation, continuous 2D arch movement, same compact chat on phone/desktop, no horizontal page scrolling; desktop/privacy preserved. Not a physical iPhone check.');
});

test('spaces and lifts one moving card, keeps labels attached, and plays labelled demo media', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto('/');
  const carousel = page.getByRole('region', { name: 'Testimonial examples' });
  const card = page.locator('.text-card');
  const firstX = await card.evaluate(element => element.getBoundingClientRect().x);
  await expect.poll(() => card.evaluate(element => element.getBoundingClientRect().x)).toBeLessThan(firstX - 4);
  const movingCard = await card.boundingBox();
  expect(movingCard).not.toBeNull();
  await page.mouse.move(movingCard!.x + movingCard!.width / 2, movingCard!.y + movingCard!.height / 2);
  await expect(carousel).toHaveAttribute('data-paused', 'true');
  await expect(card).toHaveClass(/is-selected/);
  await expect.poll(() => card.evaluate(element => element.style.transform)).toContain('scale(1.06)');
  expect(await page.locator('.carousel-cards').evaluate(element => getComputedStyle(element).transform)).toBe('none');
  await expect(page.locator('.video-card')).not.toHaveClass(/is-selected/);
  await expect(card.locator('.card-annotation')).toHaveText('text message');
  const frozen = await card.evaluate(element => element.style.transform);
  const later = await card.evaluate(element => new Promise<string>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve(element.style.transform)))));
  expect(later).toBe(frozen);
  const spaces = await page.locator('.text-card, .voice-card, .video-card').evaluateAll(elements => {
    const rectangles = elements.map(e => e.getBoundingClientRect()).sort((a, b) => a.left - b.left);
    return rectangles.slice(1).map((r, i) => r.left - rectangles[i].right);
  });
  expect(Math.min(...spaces)).toBeGreaterThan(8);
  const voice = page.locator('.voice-card');
  await voice.hover();
  await expect(voice).toHaveClass(/is-selected/);
  await expect(card).not.toHaveClass(/is-selected/);
  await expect(voice.getByText('Demo')).toBeVisible();
  await expect.poll(async () => await voice.locator('audio').evaluate((media: HTMLMediaElement) => !media.paused) || await voice.getByText('Tap to play').isVisible()).toBe(true);
  if (await voice.locator('audio').evaluate((media: HTMLMediaElement) => media.paused)) await voice.getByRole('button', { name: 'Play demo' }).click();
  await expect.poll(() => voice.locator('audio').evaluate((media: HTMLMediaElement) => media.currentTime)).toBeGreaterThan(.2);
  const video = page.locator('.video-card');
  await video.hover();
  await expect.poll(() => voice.locator('audio').evaluate((media: HTMLMediaElement) => media.paused)).toBe(true);
  await expect.poll(async () => await video.locator('video').evaluate((media: HTMLMediaElement) => !media.paused) || await video.getByText('Tap to play').isVisible()).toBe(true);
  if (await video.locator('video').evaluate((media: HTMLMediaElement) => media.paused)) await video.getByRole('button', { name: 'Play demo' }).click();
  await expect.poll(() => video.locator('video').evaluate((media: HTMLMediaElement) => media.currentTime)).toBeGreaterThan(.2);
  await page.mouse.move(0, 0);
  await expect.poll(() => video.locator('video').evaluate((media: HTMLMediaElement) => media.paused)).toBe(true);
  await expect(carousel).toHaveAttribute('data-paused', 'false');
  await card.dispatchEvent('pointerdown', { pointerType: 'touch' });
  await expect(card).toHaveClass(/is-selected/);
  await expect(carousel).toHaveAttribute('data-paused', 'true');
  await card.dispatchEvent('pointerdown', { pointerType: 'touch' });
  await expect(carousel).toHaveAttribute('data-paused', 'false');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(carousel).toHaveAttribute('data-paused', 'true');
  const beforeSwipe = await card.evaluate(element => element.style.transform);
  await carousel.dispatchEvent('pointerdown', { pointerType: 'touch', clientX: 200, clientY: 100 });
  await carousel.dispatchEvent('pointerup', { pointerType: 'touch', clientX: 100, clientY: 100 });
  expect(await card.evaluate(element => element.style.transform)).not.toBe(beforeSwipe);
  // A fresh tab proves hover-video playback without prior sound permission.
  const fresh = await page.context().newPage();
  await fresh.setViewportSize({ width: 1440, height: 1000 });
  await fresh.goto('/');
  const demoPhoto = fresh.locator('.before-after-preview img');
  await demoPhoto.evaluate((img: HTMLImageElement) => img.decode());
  expect(await demoPhoto.evaluate((img: HTMLImageElement) => img.naturalWidth > 0)).toBe(true);
  await expect(fresh.locator('.before-card')).toContainText('AI-generated illustration');
  const centerTop = await fresh.locator('.text-card').evaluate(e => e.getBoundingClientRect().top);
  const sideTop = await fresh.locator('.voice-card').evaluate(e => e.getBoundingClientRect().top);
  expect(sideTop).toBeGreaterThan(centerTop + 10);
  await expect(fresh.locator('body')).not.toContainText(/fictional/i);
  await expect(fresh.locator('.video-card .sender')).toContainText('Meera');
  await expect(fresh.locator('.before-card .sender')).toContainText('Meera');
  await expect(fresh.locator('.voice-card .sender')).toContainText('Ananya');
  await expect(fresh.locator('.group-trailing')).toContainText('Can someone recommend a good pediatrician nearby?');
  const freshVideo = fresh.locator('.video-card');
  await freshVideo.hover();
  await expect.poll(() => freshVideo.locator('video').evaluate((media: HTMLMediaElement) => media.currentTime)).toBeGreaterThan(.2);
  if (await freshVideo.locator('video').evaluate((media: HTMLMediaElement) => media.muted)) {
    await expect(freshVideo.getByText('Tap for sound')).toBeVisible();
    await freshVideo.getByRole('button', { name: 'Play demo with sound' }).click();
    await expect.poll(() => freshVideo.locator('video').evaluate((media: HTMLMediaElement) => media.muted)).toBe(false);
  }
  await fresh.close();
  console.log('PASS: separated cards; one selected card lifts while track freezes; attached handwritten labels; demo audio/video playback with click fallback; stop on exit; touch pause/resume; reduced-motion support.');
});
